services:
  db:
    image: postgres:latest
    container_name: gps-no-sync-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  influx:
    image: influxdb:latest
    container_name: gps-no-sync-influx
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx/data:/var/lib/influxdb2
      - ./data/influx/config:/etc/influxdb2
    restart: unless-stopped